Mobile viewport
oslabs-beta/ReacType pull request #6
Opened 2021-03-11 19:42 UTC by eddypjr

**Types of Changes**
- [ ]  Added function undoRedoKey(RightContainer.tsx line 209) to keybind Undo and Redo actions
- [ ] Works for both Mac and Windows

**Purpose**
- To allow users to Undo and Redo actions with ease.

**Tutorial**
Mac
Undo: Command + z
Redo: Command + shift + z

Windows:
Undo: Control + z
Redo: Control + shift + z

**Screenshots**
<img width="1086" alt="Screen Shot 2021-03-11 at 11 32 29 AM" src="https://user-images.githubusercontent.com/69879756/110844896-d2329880-825e-11eb-8302-00481747a0e3.png">

2021-03-12 04:15 UTC, khuongdn16 requested changes
Please see my comments.

2021-03-12 04:15 UTC, khuongdn16 commented on app/src/reducers/componentReducer.ts
> +import { isObjectType } from 'graphql';
Can you share the reason for this import ? I don't think this file needs grapql functions.

2021-03-12 04:15 UTC, khuongdn16 commented on app/src/containers/RightContainer.tsx
> +  };
Please advise why we need to remove the event listener here? It is not neccessary to keep the listener active to listen for the key press?

2021-03-13 19:31 UTC, khuongdn16 approved these changes
Looks good.

2021-03-13 19:31 UTC, Anthonytorrero approved these changes

2021-03-13 19:32 UTC, khuongdn16 commented
Approved.

2021-03-13 19:33 UTC, merged